// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateBill(arg1:main.CreateBillInput):Promise<main.BillDetail>;

export function ExportData(arg1:string):Promise<string>;

export function GetAllTags():Promise<Array<main.TagItem>>;

export function GetBillDetail(arg1:number):Promise<main.BillDetail>;

export function GetBills(arg1:string):Promise<Array<main.BillItem>>;

export function GetCategoryTree():Promise<Array<main.CategoryNode>>;

export function GetConfig():Promise<main.AppConfig>;

export function GetConfigStatus():Promise<main.ConfigStatus>;

export function GetDashboardStats(arg1:string):Promise<main.DashboardStats>;

export function GetDeletedBills(arg1:string):Promise<Array<main.BillItem>>;

export function GetMonthlyStats(arg1:string):Promise<string>;

export function GetMonthlySummary(arg1:string):Promise<string>;

export function GetVerify():Promise<string>;

export function OpenPath(arg1:string):Promise<void>;

export function RestoreBill(arg1:number):Promise<void>;

export function RunGitHubBackup(arg1:string):Promise<string>;

export function RunLocalBackup(arg1:string):Promise<string>;

export function RunReport(arg1:string):Promise<string>;

export function SoftDeleteBill(arg1:number):Promise<void>;

export function UpdateBillBasic(arg1:main.UpdateBillBasicInput):Promise<main.BillDetail>;

export function UpdateBillCategory(arg1:number,arg2:string,arg3:string):Promise<void>;

export function UpdateBillNote(arg1:number,arg2:string):Promise<void>;

export function UpdateBillTags(arg1:number,arg2:Array<string>):Promise<void>;

export function UpdateConfig(arg1:main.AppConfig):Promise<void>;
