// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateBill(arg1) {
  return window['go']['main']['App']['CreateBill'](arg1);
}

export function CreateCategory(arg1) {
  return window['go']['main']['App']['CreateCategory'](arg1);
}

export function CreateMerchant(arg1) {
  return window['go']['main']['App']['CreateMerchant'](arg1);
}

export function CreateTag(arg1) {
  return window['go']['main']['App']['CreateTag'](arg1);
}

export function DeleteCategory(arg1) {
  return window['go']['main']['App']['DeleteCategory'](arg1);
}

export function DeleteMerchant(arg1) {
  return window['go']['main']['App']['DeleteMerchant'](arg1);
}

export function DeleteTag(arg1) {
  return window['go']['main']['App']['DeleteTag'](arg1);
}

export function ExportData(arg1) {
  return window['go']['main']['App']['ExportData'](arg1);
}

export function GetAllTags() {
  return window['go']['main']['App']['GetAllTags']();
}

export function GetBillDetail(arg1) {
  return window['go']['main']['App']['GetBillDetail'](arg1);
}

export function GetBills(arg1) {
  return window['go']['main']['App']['GetBills'](arg1);
}

export function GetCategoryTree() {
  return window['go']['main']['App']['GetCategoryTree']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConfigStatus() {
  return window['go']['main']['App']['GetConfigStatus']();
}

export function GetDashboardStats(arg1) {
  return window['go']['main']['App']['GetDashboardStats'](arg1);
}

export function GetDeletedBills(arg1) {
  return window['go']['main']['App']['GetDeletedBills'](arg1);
}

export function GetMonthlyStats(arg1) {
  return window['go']['main']['App']['GetMonthlyStats'](arg1);
}

export function GetMonthlySummary(arg1) {
  return window['go']['main']['App']['GetMonthlySummary'](arg1);
}

export function GetVerify() {
  return window['go']['main']['App']['GetVerify']();
}

export function ListCategories(arg1) {
  return window['go']['main']['App']['ListCategories'](arg1);
}

export function ListMerchants(arg1) {
  return window['go']['main']['App']['ListMerchants'](arg1);
}

export function ListTags(arg1) {
  return window['go']['main']['App']['ListTags'](arg1);
}

export function MergeTags(arg1) {
  return window['go']['main']['App']['MergeTags'](arg1);
}

export function OpenPath(arg1) {
  return window['go']['main']['App']['OpenPath'](arg1);
}

export function RestoreBill(arg1) {
  return window['go']['main']['App']['RestoreBill'](arg1);
}

export function RunGitHubBackup(arg1) {
  return window['go']['main']['App']['RunGitHubBackup'](arg1);
}

export function RunLocalBackup(arg1) {
  return window['go']['main']['App']['RunLocalBackup'](arg1);
}

export function RunReport(arg1) {
  return window['go']['main']['App']['RunReport'](arg1);
}

export function SetCategoryActive(arg1, arg2) {
  return window['go']['main']['App']['SetCategoryActive'](arg1, arg2);
}

export function SetMerchantActive(arg1, arg2) {
  return window['go']['main']['App']['SetMerchantActive'](arg1, arg2);
}

export function SetTagActive(arg1, arg2) {
  return window['go']['main']['App']['SetTagActive'](arg1, arg2);
}

export function SoftDeleteBill(arg1) {
  return window['go']['main']['App']['SoftDeleteBill'](arg1);
}

export function UpdateBillBasic(arg1) {
  return window['go']['main']['App']['UpdateBillBasic'](arg1);
}

export function UpdateBillCategory(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateBillCategory'](arg1, arg2, arg3);
}

export function UpdateBillNote(arg1, arg2) {
  return window['go']['main']['App']['UpdateBillNote'](arg1, arg2);
}

export function UpdateBillTags(arg1, arg2) {
  return window['go']['main']['App']['UpdateBillTags'](arg1, arg2);
}

export function UpdateCategory(arg1) {
  return window['go']['main']['App']['UpdateCategory'](arg1);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}

export function UpdateMerchant(arg1) {
  return window['go']['main']['App']['UpdateMerchant'](arg1);
}

export function UpdateTag(arg1) {
  return window['go']['main']['App']['UpdateTag'](arg1);
}
