// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMonthlyStats(arg1:string):Promise<string>;

export function GetMonthlySummary(arg1:string):Promise<string>;

export function GetVerify():Promise<string>;

export function RunGitHubBackup(arg1:string):Promise<string>;
