// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMonthlyStats(arg1) {
  return window['go']['main']['App']['GetMonthlyStats'](arg1);
}

export function GetMonthlySummary(arg1) {
  return window['go']['main']['App']['GetMonthlySummary'](arg1);
}

export function GetVerify() {
  return window['go']['main']['App']['GetVerify']();
}

export function RunGitHubBackup(arg1) {
  return window['go']['main']['App']['RunGitHubBackup'](arg1);
}
